import express from 'express';
import healthRouter from './health/health.router';
import metricsRouter from './metrics/metrics.router';
import docsRouter from './docs/docs.router';
import accountRouter from './account/account.router';
import widgetsRouter from './widgets/widgets.router';
import poolsRouter from './pools/pools.router';
import membersRouter from './members/members.router';
import rewardsRouter from './rewards/reward.router';
import withdrawalsRouter from './withdrawals/withdrawals.router';
import membershipsRouter from './memberships/memberships.router';
import tokenRouter from './token/token.router';
import pointRewardsRouter from './point-rewards/point-rewards.router';
import pointBalancesRouter from './point-balances/point-balances.router';
import promotionsRouter from './promotions/promotions.router';
import depositsRouter from './deposits/deposits.router';
import paymentsRouter from './payments/payments.router';
import erc721Router from './erc721/erc721.router';
import erc721MetadataRouter from './erc721/metadata/metadata.router';
import uploadRouter from './upload/upload.router';
import erc20Router from './erc20/erc20.router';
import transactionsRouter from './transactions/transactions.router';
import erc20SwapRuleRouter from './swaprules/swaprules.router';
import clientRouter from './client/client.router';
import erc20SwapRouter from './swaps/swaps.router';
import claimsRouter from './claims/claims.router';
import brandsRouter from './brands/brands.router';
import walletsRouter from './wallets/wallets.router';
import { checkJwt, corsHandler } from '@thxnetwork/api/middlewares';

const router = express.Router();

router.use('/ping', (_req, res) => res.send('pong'));
router.use('/health', healthRouter);
router.use('/token', tokenRouter);
router.use('/docs', docsRouter);
router.use('/metadata', erc721MetadataRouter);
router.use('/payments', paymentsRouter);
router.use('/point-rewards', pointRewardsRouter);

router.use(checkJwt);
router.use(corsHandler);
router.use('/point-balances', pointBalancesRouter);
router.use('/account', accountRouter);
router.use('/pools', poolsRouter);
router.use('/metrics', metricsRouter);
router.use('/erc20', erc20Router);
router.use('/erc721', erc721Router);
router.use('/deposits', depositsRouter);
router.use('/members', membersRouter);
router.use('/memberships', membershipsRouter);
router.use('/promotions', promotionsRouter);
router.use('/rewards', rewardsRouter);
router.use('/widgets', widgetsRouter);
router.use('/withdrawals', withdrawalsRouter);
router.use('/transactions', transactionsRouter);
router.use('/swaprules', erc20SwapRuleRouter);
router.use('/upload', uploadRouter);
router.use('/swaps', erc20SwapRouter);
router.use('/brands', brandsRouter);
router.use('/clients', clientRouter);
router.use('/transactions', transactionsRouter);
router.use('/claims', claimsRouter);
router.use('/wallets', walletsRouter);

export default router;
