export { Client as THXClient } from './lib/client';
export { default as TorusManager } from './lib/managers/TorusManager';
export { default as CredentialManager } from './lib/managers/CredentialManager';
export { default as ERC20Manager } from './lib/managers/ERC20Manager';
export { default as ERC721Manager } from './lib/managers/ERC721Manager';
export { default as RequestManager } from './lib/managers/RequestManager';
export { default as AccountManager } from './lib/managers/AccountManager';
export { default as SessionManager } from './lib/managers/SessionManager';
export { default as UserManager } from './lib/managers/UserManager';
