export enum JobType {
    UpdateParticipantRanks = 'updateParticipantRanks',
    UpdateCampaignRanks = 'updateCampaignRanks',
    UpdatePendingTransactions = 'updatePendingTransactions',
    CreateTwitterQuests = 'createTwitterQuests',
    SendCampaignReport = 'sendPoolAnalyticsReport',
    MigrateWallets = 'migrateWallets',
    DeploySafe = 'deploySafe',
    CreateQuestEntry = 'createQuestEntry',
    RequestAttemp = 'requestAttempt',
    UpdateTwitterLikeCache = 'updateTwitterLikeCache',
    UpdateTwitterRepostCache = 'updateTwitterRepostCache',
    UpsertInvoices = 'upsertInvoices',
    UpdatePrices = 'updatePrices',
}
